# Our desired pipeline using only a Nix shell environment
# Test comment
name: Check and build the TODOs API (Nix)

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  check_nix:
    name: Check TODOs API
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set up Git credentials
        run: echo "machine github.com login ${{ secrets.GH_TOKEN }}" > ~/.netrc
      
      
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main

      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      # Nix-specific logic begins here
      - name: Check Rust formatting
        run: |
          nix develop --command \
            cargo fmt --check

      - name: Check spelling
        run: |
          nix develop --command \
            codespell \
              --skip target,.git \
              --ignore-words-list crate
      # - name: Audit Rust code
      #   run: |
      #     nix develop --command \
      #       cargo-deny check
      # - name: editorconfig check
      #   run: |
      #     nix develop --command \
      #       eclint \
      #         -exclude "Cargo.lock"


  build_and_test_nix:
    name: Test and build TODOs API
    needs: check_nix
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Set up Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: todos-app-${{ hashFiles('**/Cargo.lock') }}
      - name: Test TODOs API
        run: |
          nix develop --command \
            cargo test
      - name: Build TODOs API
        run: nix build .#todos

      # https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/docker/examples.nix
      - name: Build TODOs Docker image
        run: nix build .#docker
